#
# Module manifest for module 'PsXisfReader'
#
# Generated by: Jonathan W. MacCollum
#
# Generated on: 5/18/2020
#

@{
    RootModule="PixInsightPreProcessing.psm1"
ModuleVersion = '1.0.16'
GUID = '67d4833d-8c25-489b-893e-58f62eb0057b'
Author = 'Jonathan W. MacCollum'
Copyright = '(c) Jonathan W. MacCollum. All rights reserved.'

Description = 'A set of Cmdlets for maintaining images acquired and saved in XISF format with the goal of automating pre-processing processing workflows.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '7.0'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
ScriptsToProcess = @(
    "XisfFitsStats.ps1"
)

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @(
    "PsXisfReader.psm1"
)

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    'Get-XisfFitsStats'
    'Get-XisfImageScale'
    'Measure-ExposureTime'
    'Get-MoonPercentIlluminated'
    'Read-XisfSignature'
    'Read-XisfHeader'
    'Get-XisfProperties'
    'Get-XisfHeader'
    'Wait-PixInsightInstance'
    'Get-PixInsightInstance'
    'Start-PixInsight'
    'Invoke-PixInsightScript'
    'Format-PiPath'
    'Invoke-PIIntegrationScript'
    'Invoke-PICalibrationScript'
    'Invoke-PiDarkIntegration'
    'Invoke-PiFlatIntegration'
    'Invoke-PiFlatCalibration'
    'Invoke-PiLightCalibration'
    'Invoke-PiCosmeticCorrection'
    'Invoke-PiDebayer'
    'Invoke-BiasFrameSorting'
    'Invoke-DarkFrameSorting'
    'Invoke-DarkFlatFrameSorting'
    'Get-XisfFile'
    'Skip-PathsContainingTokens'
    'Get-XisfLightFrames'
    'Get-XisfDarkFrames'
    'Invoke-FlatFrameSorting'
    'Get-CalibrationFile'
    'Invoke-LightFrameSorting'
    'Start-PiSubframeSelectorWeighting'
    'Invoke-PiStarAlignment'
    'Start-PiCometAlignment'
    'Invoke-PiLightIntegration'
    'New-XisfPreprocessingState'
    'Get-XisfCalibrationState'
    'Get-XisfCosmeticCorrectionState'
    'Get-XisfSubframeSelectorState'
    'Get-XisfDebayerState'
    'Get-XisfSubframeSelectorState'
    'Get-XisfAlignedState'
    'Invoke-XisfPostCalibrationColorImageWorkflow'
    'Invoke-XisfPostCalibrationMonochromeImageWorkflow'
    'Get-MasterDarkLibrary'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @(
)

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @()

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

